# Generated by Django 4.0.2 on 2022-02-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter album name', max_length=255)),
                ('producer', models.CharField(default='The Family Chorale', help_text="Enter producer's name", max_length=255, null=True)),
                ('release_date', models.DateField()),
                ('album_art', models.ImageField(default='media/album_art/default.png', upload_to='media/album_art/')),
                ('detail', models.TextField()),
                ('feature', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(default='posters/default.jpeg', upload_to='posters/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('stop_time', models.TimeField(null=True)),
                ('location', models.CharField(default='Kisumu', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Enter your age')),
                ('leaders_pic', models.ImageField(upload_to='media/leaders/')),
                ('phone', models.CharField(help_text='Enter a number beginning with 07', max_length=10)),
                ('position', models.CharField(help_text='Hierarchy', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Enter your age')),
                ('phone', models.CharField(help_text='Enter a number beginning with 07', max_length=10)),
                ('church', models.CharField(help_text='Church you belong to', max_length=255, null=True)),
                ('note', models.CharField(blank=True, choices=[('ALTO', 'Alto'), ('BASE', 'Base'), ('TENHA', 'Tenha')], max_length=10)),
                ('residence', models.CharField(max_length=255, null=True)),
                ('sample', models.FileField(help_text='sample of your voice', null=True, upload_to='media/sample/')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Track's name", max_length=255)),
                ('link', models.TextField(blank=True, help_text='Enter the youtube video link', null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='media/audio/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_chorale.album')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='upload picture', upload_to='media/gallery/')),
                ('feature', models.BooleanField(default=False)),
                ('event', models.ForeignKey(help_text='Event where picture was taken', null=True, on_delete=django.db.models.deletion.CASCADE, to='family_chorale.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventGoer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Enter your age')),
                ('phone', models.CharField(help_text='Enter a number beginning with 07', max_length=10)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family_chorale.event')),
            ],
        ),
    ]
