# Generated by Django 4.0.2 on 2022-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='age',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='phone',
        ),
        migrations.AlterField(
            model_name='leader',
            name='leaders_pic',
            field=models.ImageField(default='media/leaders/default.png', upload_to='media/leaders/'),
        ),
    ]
