# Generated by Django 4.0.2 on 2022-02-22 09:18

from django.db import migrations, models
import django.db.models.deletion
import family_chorale.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='leader',
            name='age',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sample',
        ),
        migrations.AddField(
            model_name='member',
            name='voice_sample',
            field=models.FileField(help_text='sample of your voice in aac or mp3 format', null=True, upload_to='media/sample/'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='phone',
            field=models.CharField(help_text='Enter a number beginning with 07', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leaders_pic',
            field=models.ImageField(default='media/leaders/default.png', upload_to='media/leaders/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(help_text='Enter your age', validators=[family_chorale.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='member',
            name='church',
            field=models.CharField(help_text='Church you belong to', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='note',
            field=models.CharField(help_text='Voice note you play', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='residence',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family_chorale.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='link',
            field=models.TextField(help_text='Enter the youtube video link'),
        ),
    ]
