# Generated by Django 4.0.2 on 2022-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0002_remove_leader_age_remove_leader_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='note',
            field=models.CharField(help_text='Voice note you play', max_length=255),
        ),
    ]
