# Generated by Django 4.0.2 on 2022-02-22 10:15

from django.db import migrations, models
import family_chorale.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0002_alter_event_options_remove_leader_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.ImageField(default='media/album_art/default.png', upload_to='media/album_art/', validators=[family_chorale.models.validate_pic_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='posters/default.jpeg', upload_to='posters/', validators=[family_chorale.models.validate_pic_size]),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(help_text='upload picture', upload_to='media/gallery/', validators=[family_chorale.models.validate_pic_size]),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leaders_pic',
            field=models.ImageField(default='media/leaders/default.png', upload_to='media/leaders/', validators=[family_chorale.models.validate_pic_size]),
        ),
    ]
