# Generated by Django 4.0.2 on 2022-02-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0002_alter_event_options_remove_leader_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgoer',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='eventgoer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family_chorale.eventgoer'),
        ),
    ]
