# Generated by Django 4.0.2 on 2022-02-22 10:21

from django.db import migrations, models
import family_chorale.models


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0003_alter_album_album_art_alter_event_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/audio/', validators=[family_chorale.models.validate_audio]),
        ),
    ]
