# Generated by Django 4.0.2 on 2022-02-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0004_remove_eventgoer_event_event_eventgoer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventgoer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_chorale.eventgoer'),
        ),
    ]
