# Generated by Django 4.0.2 on 2022-02-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0005_alter_event_eventgoer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventgoer',
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family_chorale.event'),
        ),
    ]
