# Generated by Django 4.0.2 on 2022-02-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0006_remove_event_eventgoer_eventgoer_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
