# Generated by Django 4.0.2 on 2022-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0007_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='sample',
            new_name='voice_sample',
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='name',
            field=models.CharField(help_text='Enter your full name', max_length=255, unique=True),
        ),
    ]
