# Generated by Django 4.0.2 on 2022-02-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0008_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgoer',
            name='name',
            field=models.CharField(help_text='Enter your full name', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='phone',
            field=models.CharField(help_text='Enter a number beginning with 07', max_length=10, unique=True),
        ),
    ]
