# Generated by Django 4.0.2 on 2022-02-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0009_alter_eventgoer_name_alter_eventgoer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family_chorale.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='link',
            field=models.TextField(help_text='Enter the youtube video link'),
        ),
    ]
